// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS0vlFmrClykMANxWErW5ttcteS3WQoys',
    appId: '1:64181750949:web:ea314320889f850e41914c',
    messagingSenderId: '64181750949',
    projectId: 'testing-10de4',
    authDomain: 'testing-10de4.firebaseapp.com',
    databaseURL: 'https://testing-10de4-default-rtdb.firebaseio.com',
    storageBucket: 'testing-10de4.appspot.com',
    measurementId: 'G-1MW27H2HS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc6B4sOBvutgUlbGpI3VykbeyfUVKdt-s',
    appId: '1:64181750949:android:727901dce10ff02a41914c',
    messagingSenderId: '64181750949',
    projectId: 'testing-10de4',
    databaseURL: 'https://testing-10de4-default-rtdb.firebaseio.com',
    storageBucket: 'testing-10de4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu5Ls67i9DYxI2nj7I_EJXaBX6cLEuD8E',
    appId: '1:64181750949:ios:aa4c16b7075e39a641914c',
    messagingSenderId: '64181750949',
    projectId: 'testing-10de4',
    databaseURL: 'https://testing-10de4-default-rtdb.firebaseio.com',
    storageBucket: 'testing-10de4.appspot.com',
    iosClientId: '64181750949-t50f80tdaefa42anqa0620uao2gduhce.apps.googleusercontent.com',
    iosBundleId: 'com.example.testcli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu5Ls67i9DYxI2nj7I_EJXaBX6cLEuD8E',
    appId: '1:64181750949:ios:aa4c16b7075e39a641914c',
    messagingSenderId: '64181750949',
    projectId: 'testing-10de4',
    databaseURL: 'https://testing-10de4-default-rtdb.firebaseio.com',
    storageBucket: 'testing-10de4.appspot.com',
    iosClientId: '64181750949-t50f80tdaefa42anqa0620uao2gduhce.apps.googleusercontent.com',
    iosBundleId: 'com.example.testcli',
  );
}
